-- Demo blog posts for Saudi Petsitters (idempotent upsert)

INSERT INTO blog_posts (
  id,
  title,
  slug,
  excerpt,
  content,
  cover_image,
  category,
  author_name,
  published,
  status,
  published_at,
  tags,
  seo_title,
  seo_description,
  featured,
  created_by
) VALUES
  (
    '55555555-5555-4555-8555-111111111111',
    'How to Prepare Your Pet for Summer in Saudi Arabia',
    'prepare-pet-for-saudi-summer',
    'Practical heat-safety tips for walks, hydration, grooming, and emergency warning signs.',
    '<p>Saudi summers can be challenging for pets. With temperatures regularly exceeding 40°C, owners need a proactive plan to keep animals safe, comfortable, and healthy.</p><h2>Walk smarter, not longer</h2><p>Keep walks short and schedule them before sunrise or after sunset. Hot pavement can burn paw pads in seconds — if you cannot hold your hand on the ground for five seconds, it is too hot for your pet.</p><h2>Hydration and shade</h2><ul><li>Provide constant access to fresh, cool water indoors and outdoors.</li><li>Never leave pets in parked cars, even for a few minutes.</li><li>Create shaded rest areas if your pet spends time in a yard or balcony.</li></ul><h2>Warning signs to watch for</h2><p>Heavy panting, weakness, drooling, vomiting, or confusion can signal heatstroke. Move your pet to a cool area immediately and contact a veterinarian without delay.</p>',
    'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=1200&q=85',
    'pet_care',
    'Saudi Petsitters Team',
    true,
    'published',
    now() - interval '14 days',
    ARRAY['summer', 'heat-safety', 'saudi-arabia'],
    'Summer Pet Care Guide for Saudi Arabia',
    'Heat-safety tips for pet walks, hydration, grooming, and emergency warning signs in Saudi summers.',
    true,
    'seed@saudipetsitters.com'
  ),
  (
    '55555555-5555-4555-8555-222222222222',
    'Vaccination Basics for New Pet Owners',
    'vaccination-basics-new-pet-owners',
    'A simple guide to core vaccines and when to ask your vet for a tailored schedule.',
    '<p>Bringing a new pet home is exciting — and vaccinations are one of the most important steps in protecting their long-term health.</p><h2>Start with a wellness visit</h2><p>Vaccination plans depend on species, age, lifestyle, and previous medical history. Schedule a wellness check within the first week, bring any adoption or breeder records, and ask your veterinarian to build a schedule tailored to your pet.</p><h2>Core vaccines to discuss</h2><ul><li>Rabies (required in many regions)</li><li>Combination vaccines for dogs (distemper, parvovirus, adenovirus)</li><li>Core feline vaccines (panleukopenia, calicivirus, herpesvirus)</li><li>Parasite prevention for fleas, ticks, and worms</li></ul><p>Keep a simple vaccination log and set reminders for boosters. Your vet clinic on Saudi Petsitters can help you stay on track.</p>',
    'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?w=1200&q=85',
    'health',
    'Dr. Reem Al-Salem',
    true,
    'published',
    now() - interval '10 days',
    ARRAY['vaccination', 'vet-care', 'new-owners'],
    'Vaccination Basics for New Pet Owners',
    'Core vaccines, wellness visits, and booster schedules explained for new pet owners in Saudi Arabia.',
    false,
    'seed@saudipetsitters.com'
  ),
  (
    '55555555-5555-4555-8555-333333333333',
    'Choosing the Right Pet Sitter',
    'choosing-the-right-pet-sitter',
    'Questions to ask before boarding, daycare, or home-sitting bookings.',
    '<p>Finding trustworthy care for your pet while you travel or work long hours can feel overwhelming. The right sitter should feel like an extension of your own routine.</p><h2>What to ask every sitter</h2><ul><li>How many pets do you host at once, and what species do you accept?</li><li>Can you follow my pet''s feeding, medication, and exercise schedule?</li><li>What is your emergency plan if my pet becomes ill?</li><li>How often will you send updates and photos?</li></ul><h2>Red flags to avoid</h2><p>Vague answers about experience, unwillingness to share references, or no clear cancellation policy are worth noting. On Saudi Petsitters, verified hosts display ratings, services, and availability to help you compare options confidently.</p>',
    'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=1200&q=85',
    'lifestyle',
    'Saudi Petsitters Team',
    true,
    'published',
    now() - interval '7 days',
    ARRAY['pet-sitting', 'boarding', 'travel'],
    'How to Choose the Right Pet Sitter',
    'Essential questions for boarding, daycare, and home-sitting before you book a pet sitter.',
    false,
    'seed@saudipetsitters.com'
  ),
  (
    '55555555-5555-4555-8555-444444444444',
    '5 Essential Commands Every Dog Should Know',
    'essential-dog-training-commands',
    'Sit, stay, come, leave it, and heel — the foundation for a well-behaved companion.',
    '<p>Training builds trust between you and your dog. These five commands form the foundation for safer walks, calmer vet visits, and better social interactions.</p><h2>1. Sit</h2><p>The easiest starting point. Use a treat above the nose, guide into a sit, and reward immediately. Practice in short sessions of 5–10 minutes.</p><h2>2. Stay</h2><p>Once sit is reliable, add duration and distance gradually. Always release with a clear cue like "okay."</p><h2>3. Come</h2><p>Make coming to you the best thing that happens all day — high-value treats and enthusiastic praise work wonders.</p><h2>4. Leave it</h2><p>Critical for street safety. Reward ignoring distractions on walks and around food.</p><h2>5. Heel</h2><p>Loose-leash walking reduces pulling and makes summer evening walks more enjoyable for both of you.</p>',
    'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=1200&q=85',
    'training',
    'Mohammed Al-Qahtani',
    true,
    'published',
    now() - interval '5 days',
    ARRAY['dog-training', 'obedience', 'puppies'],
    '5 Essential Dog Training Commands',
    'Teach sit, stay, come, leave it, and heel with practical tips for Saudi pet owners.',
    false,
    'seed@saudipetsitters.com'
  ),
  (
    '55555555-5555-4555-8555-555555555555',
    'A Beginner''s Guide to Pet Nutrition',
    'beginners-guide-pet-nutrition',
    'How to read labels, portion meals correctly, and avoid common feeding mistakes.',
    '<p>Good nutrition is the backbone of a long, healthy life for your pet. With so many brands and diets available, a few simple principles go a long way.</p><h2>Read the label</h2><p>Look for named protein sources (chicken, lamb, fish) as the first ingredient. Avoid foods heavy in fillers if your vet recommends a higher-quality diet.</p><h2>Portion control matters</h2><p>Overfeeding is one of the most common causes of obesity in pets. Use the feeding guide on the package as a starting point, then adjust based on your vet''s advice and your pet''s activity level.</p><h2>Species-specific needs</h2><ul><li>Cats are obligate carnivores — they need animal protein.</li><li>Dogs benefit from balanced commercial diets matched to life stage.</li><li>Rabbits and small pets need hay, fresh greens, and limited pellets.</li></ul><p>When in doubt, ask your veterinarian before switching foods abruptly.</p>',
    'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=1200&q=85',
    'nutrition',
    'Dr. Reem Al-Salem',
    true,
    'published',
    now() - interval '3 days',
    ARRAY['nutrition', 'feeding', 'wellness'],
    'Beginner''s Guide to Pet Nutrition',
    'Label reading, portion control, and species-specific feeding tips for pet owners.',
    false,
    'seed@saudipetsitters.com'
  ),
  (
    '55555555-5555-4555-8555-666666666666',
    'Saudi Petsitters Launches Nationwide Vet Directory',
    'saudi-petsitters-vet-directory-launch',
    'Find approved clinics, book appointments, and access pet health resources in one place.',
    '<p>We are excited to announce the expansion of our vet directory across Saudi Arabia, making it easier than ever to find trusted clinics near you.</p><h2>What is new</h2><ul><li>Search clinics by city, specialty, and services offered.</li><li>Book appointments directly through the platform.</li><li>Read verified reviews from other pet owners.</li><li>Access our growing library of pet care articles.</li></ul><p>Whether you need a routine checkup, emergency care referral, or specialist consultation, Saudi Petsitters connects you with the right clinic faster.</p><p><strong>Explore the directory today</strong> and give your pet the care they deserve.</p>',
    'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=1200&q=85',
    'news',
    'Saudi Petsitters Team',
    true,
    'published',
    now() - interval '1 day',
    ARRAY['news', 'vet-directory', 'platform'],
    'Saudi Petsitters Vet Directory Launch',
    'Nationwide vet directory with appointments, reviews, and pet health resources.',
    false,
    'seed@saudipetsitters.com'
  )
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  cover_image = EXCLUDED.cover_image,
  category = EXCLUDED.category,
  author_name = EXCLUDED.author_name,
  published = EXCLUDED.published,
  status = EXCLUDED.status,
  published_at = EXCLUDED.published_at,
  tags = EXCLUDED.tags,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  featured = EXCLUDED.featured,
  updated_at = now();

-- Demo approved comments on the featured summer post
INSERT INTO blog_comments (
  id,
  post_id,
  author_name,
  author_email,
  content,
  status
) VALUES
  (
    '88888888-8888-4888-8888-111111111111',
    '55555555-5555-4555-8555-111111111111',
    'Fatima Al-Rashid',
    'fatima@example.com',
    'This was so helpful! I started walking my husky at 5:30 AM and it made a huge difference.',
    'approved'
  ),
  (
    '88888888-8888-4888-8888-222222222222',
    '55555555-5555-4555-8555-111111111111',
    'Omar Hassan',
    'omar@example.com',
    'Great reminder about hot pavement. I had no idea it could burn paws that quickly.',
    'approved'
  ),
  (
    '88888888-8888-4888-8888-333333333333',
    '55555555-5555-4555-8555-222222222222',
    'Layla Mansour',
    'layla@example.com',
    'Just adopted a kitten — this vaccination timeline is exactly what I needed. Thank you!',
    'approved'
  )
ON CONFLICT (id) DO UPDATE SET
  content = EXCLUDED.content,
  status = EXCLUDED.status,
  updated_at = now();
